ubuntu: handle release_ids containing dashes
Packages like:
linux-headers-5.4.0-1063-azure-cvm_5.4.0-1063.66+cvm3_amd64.deb
were not handled correctly in that release_id was considered
as '5.4.0-1063-azure'
which would also contain packages like:
linux-headers-5.4.0-1063-azure_5.4.0-1063.66_amd64.deb

leading to the following error:
ValueError: Unexpected version 5.4.0-1063/66+cvm3 from package
/workspace/ubuntu/linux-headers-5.4.0-1063-azure-cvm_5.4.0-1063.66+cvm3_amd64.deb
(expected 5.4.0-1063/66)

Change the regex so to swallow such strings and therefore yield
a different release_id and avoid such mismatch.